language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql DATABASE_TEST_NAME=omniauth_rails_test DATABASE_TEST_USERNAME=postgres
before_script:
  - psql -c 'createdatabase omniauth_rails_test' -U postgres
script:
  - rake db:migrate --trace
  - rake db:test:prepare
  - rake test
